version: '2'

services:
  web:
    build: .
    ports:
    - "8000:8080"
    volumes:
    - "data:/opt/zope/var/filestorage"
    # command: /usr/bin/tail -f /dev/null

volumes:
  data:
    driver: local
